### ISSUE TITLE
[definitions is not generated for css modules]

### ISSUE THREAD

**Issue by legomushroom** [Jimdo/typings-for-css-modules-loader#32]
Good day,

When using the `typings-for-css-modules-loader` for `CSS` modules that have only `:global` styles, the module definitions is not generated *if a file has only `:global` styles*:

```css
:global(.foo) {
  // ..
}

:global(.bar) {
  // ..
}
```

So we have to add an `empty` class name with `empty` styles on it:

```css
// useless class name with "empty" styles
// to make the types module compilation work
.empty {
  opacity: 1; // default styles
}

:global(.foo) {
  // ..
}

:global(.bar) {
  // ..
}
```

Interesting to know your thoughts regarding this, do you consider this as a `bug`?
Thanks in advance.
