### ISSUE TITLE
Should global blocks export definitions?

### ISSUE THREAD

**Issue by shirakaba** [Jimdo/typings-for-css-modules-loader#53]
When I declare a global block, no `.d.ts` declaration is emitted for it. The CSS does get written into the final file, however. This means that I get an error when trying to refer to my global style in TypeScript. Is this expected behaviour?

## Input SCSS

One global block and one default block (default is local).

```SCSS
:global {
    .fullscreen {
        position: absolute;
        left: 0px;
        top: 0px;
        width: 1280px;
        height: 720px;
    }
}

.justify_content_space_around {
    -webkit-justify-content: space-around;
    justify-content: space-around;
}
```

## Typescript invocation

```Typescript
import { locals } from '../scss/generic.scss';

// No compiler problems with the local one:
console.log(locals.justifyContentSpaceAround);

// [ERROR] TS2339: Property 'fullscreen' does not appear on type 'IGenericScss'
console.log(locals.fullscreen);
```

## Generated `.d.ts` file

Note that the global 'fullscreen' style does not get generated, and only a 'locals' property is exported (I was expecting perhaps to see a 'globals' too). Is that expected behaviour?

```Typescript
export interface IGenericScss {
  'justify_content_space_around': string;
  'justifyContentSpaceAround': string;
}

export const locals: IGenericScss;
```

## Output CSS

You'll see from the below Webpack settings that I have 'minimize' set to `true`, but I've pretty-printed it here for legibility.

```CSS
.fullscreen{
    position: absolute;
    left: 0;
    top: 0;
    width: 1280px;
    height: 720px
}
.BgmO{
    -webkit-justify-content: space-around;
    justify-content: space-around;
}
/*# sourceMappingURL=project.css.map*/
```

## Webpack config

```JS
{
    test: /\.scss$/,
    include: [ path.resolve(__dirname, "../src/scss") ],
    use: ExtractTextPlugin.extract({
        use: [
            {
                loader: 'typings-for-css-modules-loader',
                options: {
                    namedexport: true,
                    camelcase: true,
                    modules: true,
                    localIdentName: '[hash:base64:4]',
                    minimize: true,
                    importLoaders: 2
                }
            },
            {
                loader: 'postcss-loader',
                options: {
                    plugins: function () {
                        return [ autoprefixer({browsers: ["since 2013"]}) ]
                    }
                }
            },
            {loader: 'sass-loader', options: {}}
        ],
        fallback: 'style-loader'
    })
};
```
