### ISSUE TITLE
Nested classes (SASS), wrong output (CSS)

### ISSUE THREAD

**Issue by vladimir-djokic** [Jimdo/typings-for-css-modules-loader#59]
If I have a simple `foo.scss`:

```sass
.shell {

    &.path {
        background: linear-gradient(to right, #17202A, #212F3D);
    }

}
```

using `webpack.config.js`:

```js
module: {
    rules: [
        {
            test: /\.scss$/,
            use: extractTextPlugin.extract({
                fallback: "style-loader",
                use:
                    isDevBuild
                        ? "typings-for-css-modules-loader?modules&namedExport&camelCase&localIdentName=[name]_[hash:base64]&sass"
                        : "typings-for-css-modules-loader?modules&namedExport&camelCase&localIdentName=[name]_[hash:base64]&sass&minimize"
            })
        },
    ]
},
plugins: [
    ...
    new extractTextPlugin("site.css")
]
```

I get (wrong) `site.css` output:

```css
.Shell_2QRiEglvWZ4mcPjp67mAja {

    &.Shell_3D4R68K4RPOKDY6fLBEteJ {
        background: linear-gradient(to right, #17202A, #212F3D);
    }

}
```

I expected to see something like:

```css
.Shell_2QRiEglvWZ4mcPjp67mAja.Shell_3D4R68K4RPOKDY6fLBEteJ {
    background: linear-gradient(to right, #17202A, #212F3D);
}
```

Is this issue with my configuration or issue with `typings-for-css-modules-loader`?
